In [11]:
import numpy as np
import random

In [39]:
'''Decides if there is a link between two nodes depending on the probability p'''
def connect(n1,n2,p):
    if random.uniform(0,1) <= p: 
        print("Connecting ", n1.index, ' and ', n2.index)
        n1.neighbours = np.append(n1.neighbours,n2.index)
        n2.neighbours = np.append(n2.neighbours,n1.index)
        return True
    else: return False
    
    

In [40]:
class Node:
    index = 0
    spin = 0
    neighbours = np.empty([0])
    def __init__(self,index,spin):
        self.index = index
        self.spin = spin

In [117]:
class Graph:
    N=0 #number of nodes
    p=0 #probability of links between nodes
    connections = np.zeros((0,0)) #adjacency matrix
    connections_list = [] #adjacency list
    nodes = [] 
    def __init__(self,N,p):
        self.N = N
        self.p = p
        self.connections = np.zeros((N,N))
        self.nodes = []
        self.connections_list = []
        
    '''Prints the adjacency matrix'''
    def show_matrix(self):
        print(self.connections)
        
    '''Prints the adjacency list'''
    def show_list(self):
        for n in self.connections_list:
            print(n,sep='\n')
        
    
    '''Creates and adds nodes to the graph'''
    def create_nodes(self):
        for i in range(self.N):
            self.nodes.append(Node(i,random.choice([-1,1]))) #random (either 1 or -1) spin value
            
    '''Creates connections between nodes in graph in adjacency matrix'''        
    def create_connections(self):
        for i in range(self.N):
            for j in range(i+1,self.N):
                if connect(self.nodes[i],self.nodes[j],self.p):
                    self.connections[i][j] = 1
                    self.connections[j][i] = 1
                    
    '''Creates connections between nodes in graph in adjacency list'''               
    def create_connections_list(self):
        for n in self.nodes:
            self.connections_list.append(n.neighbours)
        
                    
    '''Returns total magnetization of all nodes'''               
    def magnetization(self):
        sum = 0
        for n in self.nodes:
            sum += n.spin
        return sum
        

In [107]:
def generate_graph(N,p):
    g = Graph(N,p)
    g.create_nodes()
    g.create_connections()
    g.create_connections_list()
    return g

In [118]:
g1 = generate_graph(6,0.4) #second parameter must be in range [0,1]

Connecting  1  and  4
Connecting  1  and  5
Connecting  2  and  3
Connecting  2  and  4
Connecting  3  and  4
Connecting  3  and  5


In [119]:
g1.show_matrix()

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1. 0.]
 [0. 0. 1. 0. 1. 1.]
 [0. 1. 1. 1. 0. 0.]
 [0. 1. 0. 1. 0. 0.]]


In [120]:
g1.show_list()

[]
[4. 5.]
[3. 4.]
[2. 4. 5.]
[1. 2. 3.]
[1. 3.]


In [121]:
for i in range(len(g1.nodes)):
    print(g1.nodes[i].neighbours)

[]
[4. 5.]
[3. 4.]
[2. 4. 5.]
[1. 2. 3.]
[1. 3.]


In [66]:
g1.magnetization()

-18